name: chess_system_frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_fonts: ^4.0.3
  intl: ^0.17.0
  flex_color_scheme: ^6.1.2
  go_router: ^6.0.6
  shared_preferences: ^2.1.0
  file_picker: 5.2.10
  flutter_svg: ^2.0.5

flutter:
  uses-material-design: true
